sudo: false
dist: trusty

addons:
  chrome: stable

language: node_js
node_js:
  - "4"
  - "6"
  - "8"

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache

env:
  global:
    - JOBS=1
  matrix:
    - PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-1.13
    - PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-lts-2.8
    - PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-lts-2.12
    - EMBER_TRY_SCENARIO=ember-release
    - PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-beta
    - PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-beta
    - env: PERCY_ENABLE=0 EMBER_TRY_SCENARIO=ember-canary

before_install:
  - yarn global add bower
  - bower --version

install:
  - yarn
  - bower install

script:
  # Usually, it's ok to finish the test scenario without reverting
  # to the addon's original dependency state, skipping "cleanup".
  - ember try:one $EMBER_TRY_SCENARIO test --skip-cleanup
