name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Install
        run: yarn
      - name: Validate Type Declarations
        run: echo "@next is broken for reasons" #yarn lint:ts
      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: "yarn test"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
